### ISSUE TITLE
Add GitHub topics in repo meta

### ISSUE THREAD

**Issue by jakub-g** [iteratec/wpt-filmstrip#5]
On repo main page, just below the description of the repo and the URL, you can add topic (tags) describing the repo.

I think you could add `webpagetest`, `web-performance` and similar topics.

This allows to explore different tools for similar concept, for example:
https://github.com/topics/webpagetest

**Comment by sburnicki** [comment]
Thanks for the heads-up! I added a bunch of topics :)
